// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using booking_api.Context;

#nullable disable

namespace booking_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240104133659_terceiro")]
    partial class terceiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("booking_api.Model.Clientes", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Acompanhantes")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("booking_api.Model.Compras", b =>
                {
                    b.Property<int>("Id_Compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientesId_Cliente")
                        .HasColumnType("int");

                    b.Property<int?>("PassagensId_Passagem")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_compra")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("metodo_pagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("preco_compra")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id_Compra");

                    b.HasIndex("ClientesId_Cliente");

                    b.HasIndex("PassagensId_Passagem");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("booking_api.Model.Passagens", b =>
                {
                    b.Property<int>("Id_Passagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("data_passagem")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Passagem");

                    b.ToTable("Passagens");
                });

            modelBuilder.Entity("booking_api.Model.Compras", b =>
                {
                    b.HasOne("booking_api.Model.Clientes", "Clientes")
                        .WithMany("Compras")
                        .HasForeignKey("ClientesId_Cliente");

                    b.HasOne("booking_api.Model.Passagens", "Passagens")
                        .WithMany("Compras")
                        .HasForeignKey("PassagensId_Passagem");

                    b.Navigation("Clientes");

                    b.Navigation("Passagens");
                });

            modelBuilder.Entity("booking_api.Model.Clientes", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("booking_api.Model.Passagens", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
